export const supermarketItems = [
  {
    id: 1,
    name: "Leche",
    description: "1 litro",
    stock: 20,
    availability: true,
  },
  {
    id: 2,
    name: "Pan",
    description: "1 unidad",
    stock: 50,
    availability: true,
  },
  {
    id: 3,
    name: "Huevos",
    description: "1 docena",
    stock: 30,
    availability: true,
  },
  {
    id: 4,
    name: "Arroz",
    description: "1 kilogramo",
    stock: 40,
    availability: true,
  },
  {
    id: 5,
    name: "Pollo",
    description: "1 kilogramo",
    stock: 10,
    availability: true,
  },
  {
    id: 6,
    name: "Tomate",
    description: "1 kilogramo",
    stock: 0,
    availability: false,
  },
  {
    id: 7,
    name: "Cebolla",
    description: "1 kilogramo",
    stock: 35,
    availability: true,
  },
  {
    id: 8,
    name: "Papas",
    description: "1 kilogramo",
    stock: 45,
    availability: true,
  },
  {
    id: 9,
    name: "Manzanas",
    description: "1 kilogramo",
    stock: 15,
    availability: true,
  },
  {
    id: 10,
    name: "Plátanos",
    description: "1 kilogramo",
    stock: 20,
    availability: true,
  },
];
